name:                thock
version:             0.1.0.0
github:              "rmehri01/thock"
license:             MIT
author:              "Ryan Mehri"
maintainer:          "ryan.mehri1@gmail.com"
copyright:           "Copyright (c) 2020 Ryan Mehri"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Game

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/rmehri01/thock#readme>

dependencies:
- aeson
- base >= 4.7 && < 5
- brick
- microlens
- microlens-th
- random
- text
- text-zipper
- vector
- vty

library:
  source-dirs: src

executables:
  thock-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - thock

tests:
  thock-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - thock
